In [1]:
import json, pandas as pd
data = json.load(open("../data/raw/victims_2025_01.json"))
df = pd.json_normalize(data)
print(df.shape)        # (rows, columns)
print(df.columns.tolist())
df.head()

(668, 17)
['activity', 'attackdate', 'claim_url', 'country', 'data_size', 'description', 'discovered', 'domain', 'group', 'ransom', 'screenshot', 'url', 'victim', 'press.link', 'press.source', 'press.summary', 'press']

,activity,attackdate,claim_url,country,data_size,description,discovered,domain,group,ransom,screenshot,url,victim,press.link,press.source,press.summary,press
0,Manufacturing,2025-04-02 00:00:00.000000,http://mbrlkbtq5jonaqkurjwmxftytyn2ethqvbxfu4r...,US,NaN,United States,2025-04-10T21:44:46.805057+00:00,strapsolutions.com,play,None,https://images.ransomware.live/victims/0902218...,https://www.ransomware.live/id/UEFDIFN0cmFwcGl...,PAC Strapping Products,https://www.ransomware.live/id/c3RyYXBzb2x1dGl...,https://ago.vermont.gov/document/2025-08-05-pa...,"PAC Strapping Products, Inc. experienced a ran...",NaN
1,Government & Defense,2025-01-31T18:51:48.605194+00:00,http://flock4cvoeqm4c62gyohvmncx6ck2e7ugvyqgyx...,PK,NaN,To The Organization of Punjab.gov.pk We have o...,2025-01-31T18:53:07.842755+00:00,Punjab.gov.pk,flocker,None,https://images.ransomware.live/victims/949d30e...,https://www.ransomware.live/id/UHVuamFiLmdvdi5...,Punjab.gov.pk,NaN,NaN,NaN,NaN
2,Not Found,2025-01-31T18:50:29.743075+00:00,http://flock4cvoeqm4c62gyohvmncx6ck2e7ugvyqgyx...,,NaN,To the managment of w*****e.com We have breach...,2025-01-31T18:51:45.863945+00:00,,flocker,None,https://images.ransomware.live/victims/27d5354...,https://www.ransomware.live/id/VyoqKioqZS5jb21...,W*****e.com,NaN,NaN,NaN,NaN
3,Professional Services,2025-01-31T18:49:12.576457+00:00,http://flock4cvoeqm4c62gyohvmncx6ck2e7ugvyqgyx...,,NaN,To the leadership of T**H L*******S CO LIMITED...,2025-01-31T18:50:27.488654+00:00,,flocker,None,https://images.ransomware.live/victims/032ef6d...,https://www.ransomware.live/id/VCoqKioqcC5jb21...,T*****p.com,NaN,NaN,NaN,NaN
4,Transportation,2025-01-31T18:47:55.556076+00:00,http://flock4cvoeqm4c62gyohvmncx6ck2e7ugvyqgyx...,,NaN,To the management of A** ****o We have gained ...,2025-01-31T18:49:10.364679+00:00,,flocker,None,https://images.ransomware.live/victims/1a5602e...,https://www.ransomware.live/id/QSoqLSoqKipvLmN...,A**-****o.com,NaN,NaN,NaN,NaN

In [2]:
df["country"].value_counts().head(10)

country
US    302
CA     35
       29
GB     26
IN     21
AU     20
DE     19
FR     17
BR     17
ES     13
Name: count, dtype: int64

In [3]:
df["victim"].value_counts().head(10)

victim
Land and Lakes                   2
51talk.com                       2
zapopan.gob.mx                   2
carc.gov.jo                      2
Rees NDT Inspection Services     2
realtaxcanada.com                2
topackt.com                      2
EVAS Group                       2
D-7 Roofing                      2
HIDROCARBUROS ARGENTINOS S.A.    2
Name: count, dtype: int64

In [4]:
df["activity"].value_counts().head(10)

activity
Manufacturing                      111
Professional Services              106
Technology                         105
Retail & E-Commerce                 54
Healthcare                          47
Agriculture and Food Production     41
Financial Services                  40
Transportation                      39
Government & Defense                35
Education                           28
Name: count, dtype: int64

In [5]:
df["group"].value_counts().head(10)

group
akira        71
babuk2       64
clop         60
lynx         36
ransomhub    36
funksec      35
play         32
incransom    29
qilin        26
8base        24
Name: count, dtype: int64

In [1]:
import sqlite3, pandas as pd
con = sqlite3.connect("../data/ransomware.db")
pd.read_sql("""
    SELECT sector, COUNT(*) AS victims
    FROM victims
    WHERE month >= '2025-01'
    GROUP BY sector
    ORDER BY victims DESC
    LIMIT 10
""", con)

                            sector  victims
0                    Manufacturing     2932
1            Professional Services     2533
2                       Technology     2246
3                       Healthcare     1332
4              Retail & E-Commerce     1301
5               Financial Services      928
6                          Unknown      751
7                   Transportation      688
8  Agriculture and Food Production      621
9             Government & Defense      618